[package]
name = "faker_rand"
version = "0.1.0"
authors = ["Ulysse Carion <ulysse@segment.com>"]
edition = "2018"

[dependencies]
rand = "0.8"
lazy_static = "1"

[dev-dependencies]
rand_chacha = "0.3"
